### ISSUE TITLE
Scatter/gather list - calculate_sglist_entries issue

### ISSUE THREAD

**Issue by mretallack** [ni/usb3vision#1]
Hi, 

While trying out this kernel module for usb3vision, if found an issue with the calculate_sglist_entries function. 

The bytes_to_transfer can become zero if pglist_bytes_remaining is non-zero but not enough data is available. 

I have attached the patch that fixes the issue. 

[fix-sglist-leftovers.txt](https://github.com/ni/usb3vision/files/621707/fix-sglist-leftovers.txt)

**Comment by katieensign** [comment]
Thanks for debugging this and for providing a patch -- I have added this issue to our schedule to address before the next release.

**Comment by katieensign** [comment]
Thanks again for your very helpful feedback/patch. This has been incorporated in the newest release (1.3.0), and I added more details about it in the release notes.
